### ISSUE TITLE
Stopped working since 2.5.1

### ISSUE THREAD

**Issue by gurkerl83** [vangware/window-open-promise#2]
A few days ago, with the release of 2.5.1, something broke. It was working perfectly fine with 2.5.0. The version change got declared as a patch. Something that small should not break large even when you refactored micro entirely. Looking at the dependencies involved in your project and the error message gets thrown, something has changed in micro. Has window-open-promise imported from micro before 2.5.1 also consuming the ESM module?

The exception I get is the following. Looking at the implementation of micro, the new typescript operator ?? gets used, but why gets this not converted into unreadable javascript, does it relate with the typescript lib ES2018 used in typescript compilation?

Maybe you can have a look,
Thx!

```
./node_modules/@vangware/micro/esm/arrayGroup.js 23:56
Module parse failed: Unexpected token (23:56)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     return {
|         ...groups,
>         [groupName]: arrayPush(item)(groups[groupName] ?? [])
|     };
| })({});
```

**Comment by lukeshiru** [comment]
The changes in [micro](https://micro.vangware.com) shouldn't affect `@vangware/window-open-promise` at all, that's why the version was flagged as patch (it didn't changed the API, nor added anything new, it's just a dependency upgrade).

Micro is compiled with esm and cjs targets. ESM is only modern JavaScript, and CJS does down-compilation of stuff like nullish coalescence (as you can see in the file that's throwing an error for you, in it's cjs version [here](https://unpkg.com/browse/@vangware/micro@6.0.4/cjs/arrayGroup.js)).

`@vangware/window-open-promise` is also compiled in esm and cjs, and both import from `@vangware/micro`, so the bundler/resolver needs to take care of bundling/resolving the correct path.

Initially I suggest to take a look at your webpack configuration to make sure it imports from cjs instead of esm. If that doesn't work, you should add support for nullish coalescence and optional chaining in your webpack build process (either updating TypeScript to latest if you use TypeScript, or installing the corresponding Babel plugins). Finally check your Node version (14 and above support this syntax natively).

Sorry, but I can't do anything else on my end.

Thanks for reporting!

**Comment by gurkerl83** [comment]
Thx for the explanation and hints on how to fix it on my side. I will check my setup later and provide feedback; maybe it is just my node version using node 12 LTS. Also, I have to check if this behavior is just happening in dev mode and maybe not on production.

**Comment by lukeshiru** [comment]
I'm closing this because it seems to be a problem with Webpack. From what I can gather there are some temporary solutions adding rules, or switching entirely to Rollup.

Related bug in Webpack so you can track it: https://github.com/webpack/webpack/issues/7973

**Comment by gurkerl83** [comment]
I just confirm that the latest version 2.6.0 is working again, many thx!
